// Code generated by generate.go; DO NOT EDIT.
package api

import graphql "github.com/cli/shurcooL-graphql"

// Action represents an action that can be invoked from a trigger.
type Action struct {
	Name                                             graphql.String
	DisplayName                                      graphql.String
	ID                                               graphql.String
	YamlTemplate                                     YAML
	PackageID                                        *VersionedPackageSpecifier
	Package                                          *PackageInstallation
	IsAllowedToRun                                   graphql.Boolean
	RequiresOrganizationOwnedQueriesPermissionToEdit graphql.Boolean
}

// EmailAction represents an email action.
type EmailAction struct {
	Action
	Recipients                                       []graphql.String
	SubjectTemplate                                  *graphql.String
	BodyTemplate                                     *graphql.String
	UseProxy                                         graphql.Boolean
	AttachCsv                                        graphql.Boolean
	Name                                             graphql.String
	DisplayName                                      graphql.String
	ID                                               graphql.String
	YamlTemplate                                     YAML
	PackageID                                        *VersionedPackageSpecifier
	Package                                          *PackageInstallation
	IsAllowedToRun                                   graphql.Boolean
	RequiresOrganizationOwnedQueriesPermissionToEdit graphql.Boolean
}

// HumioRepoAction represents a HumioRepo action.
type HumioRepoAction struct {
	Action
	IngestToken                                      graphql.String
	Name                                             graphql.String
	DisplayName                                      graphql.String
	ID                                               graphql.String
	YamlTemplate                                     YAML
	PackageID                                        *VersionedPackageSpecifier
	Package                                          *PackageInstallation
	IsAllowedToRun                                   graphql.Boolean
	RequiresOrganizationOwnedQueriesPermissionToEdit graphql.Boolean
}

// OpsGenieAction represents an OpsGenie action.
type OpsGenieAction struct {
	Action
	APIURL                                           graphql.String
	GenieKey                                         graphql.String
	UseProxy                                         graphql.Boolean
	Name                                             graphql.String
	DisplayName                                      graphql.String
	ID                                               graphql.String
	YamlTemplate                                     YAML
	PackageID                                        *VersionedPackageSpecifier
	Package                                          *PackageInstallation
	IsAllowedToRun                                   graphql.Boolean
	RequiresOrganizationOwnedQueriesPermissionToEdit graphql.Boolean
}

// PagerDutyAction represents a PagerDuty action.
type PagerDutyAction struct {
	Action
	Severity                                         graphql.String
	RoutingKey                                       graphql.String
	UseProxy                                         graphql.Boolean
	Name                                             graphql.String
	DisplayName                                      graphql.String
	ID                                               graphql.String
	YamlTemplate                                     YAML
	PackageID                                        *VersionedPackageSpecifier
	Package                                          *PackageInstallation
	IsAllowedToRun                                   graphql.Boolean
	RequiresOrganizationOwnedQueriesPermissionToEdit graphql.Boolean
}

// SlackAction represents a Slack action.
type SlackAction struct {
	Action
	URL                                              graphql.String
	Fields                                           []SlackFieldEntry
	UseProxy                                         graphql.Boolean
	Name                                             graphql.String
	DisplayName                                      graphql.String
	ID                                               graphql.String
	YamlTemplate                                     YAML
	PackageID                                        *VersionedPackageSpecifier
	Package                                          *PackageInstallation
	IsAllowedToRun                                   graphql.Boolean
	RequiresOrganizationOwnedQueriesPermissionToEdit graphql.Boolean
}

// SlackPostMessageAction represents a slack post-message action.
type SlackPostMessageAction struct {
	Action
	APIToken                                         graphql.String
	Channels                                         []graphql.String
	Fields                                           []SlackFieldEntry
	UseProxy                                         graphql.Boolean
	Name                                             graphql.String
	DisplayName                                      graphql.String
	ID                                               graphql.String
	YamlTemplate                                     YAML
	PackageID                                        *VersionedPackageSpecifier
	Package                                          *PackageInstallation
	IsAllowedToRun                                   graphql.Boolean
	RequiresOrganizationOwnedQueriesPermissionToEdit graphql.Boolean
}

// UploadFileAction represents an upload file action.
type UploadFileAction struct {
	Action
	FileName                                         graphql.String
	Name                                             graphql.String
	DisplayName                                      graphql.String
	ID                                               graphql.String
	YamlTemplate                                     YAML
	PackageID                                        *VersionedPackageSpecifier
	Package                                          *PackageInstallation
	IsAllowedToRun                                   graphql.Boolean
	RequiresOrganizationOwnedQueriesPermissionToEdit graphql.Boolean
}

// VictorOpsAction represents a VictorOps action.
type VictorOpsAction struct {
	Action
	MessageType                                      graphql.String
	NotifyURL                                        graphql.String
	UseProxy                                         graphql.Boolean
	Name                                             graphql.String
	DisplayName                                      graphql.String
	ID                                               graphql.String
	YamlTemplate                                     YAML
	PackageID                                        *VersionedPackageSpecifier
	Package                                          *PackageInstallation
	IsAllowedToRun                                   graphql.Boolean
	RequiresOrganizationOwnedQueriesPermissionToEdit graphql.Boolean
}

// WebhookAction represents a webhook action.
type WebhookAction struct {
	Action
	Method                                           graphql.String
	URL                                              graphql.String
	Headers                                          []HttpHeaderEntry
	BodyTemplate                                     graphql.String
	IgnoreSSL                                        graphql.Boolean
	UseProxy                                         graphql.Boolean
	Name                                             graphql.String
	DisplayName                                      graphql.String
	ID                                               graphql.String
	YamlTemplate                                     YAML
	PackageID                                        *VersionedPackageSpecifier
	Package                                          *PackageInstallation
	IsAllowedToRun                                   graphql.Boolean
	RequiresOrganizationOwnedQueriesPermissionToEdit graphql.Boolean
}

// AuthenticationMethod represents represents information about how users authenticate with Humio.
type AuthenticationMethod struct {
	Name graphql.String
}

// Auth0Authentication represents authentication through Auth0.
type Auth0Authentication struct {
	AuthenticationMethod
	Auth0Domain graphql.String
	ClientID    graphql.String
	AllowSignup graphql.Boolean
	RedirectURL graphql.String
	Name        graphql.String
}

// ByProxyAuthentication represents by proxy authentication. Authentication is provided by proxy.
type ByProxyAuthentication struct {
	AuthenticationMethod
	Name graphql.String
}

// EnterpriseOnlyAuthentication represents enterprise only authentication.
type EnterpriseOnlyAuthentication struct {
	AuthenticationMethod
	Name graphql.String
}

// NoAuthentication represents this authentication type can be used to use Humio without authentication. This should only be considered for testing and development purposes, it is not recommended for production systems and prevents Humio from doing proper Audit Logging.
type NoAuthentication struct {
	AuthenticationMethod
	Name graphql.String
}

// OAuthAuthentication represents authentication through OAuth Identity Providers.
type OAuthAuthentication struct {
	AuthenticationMethod
	Name        graphql.String
	UILoginFlow graphql.Boolean
	Google      *OAuthProvider
	GitHub      *OAuthProvider
	Bitbucket   *OAuthProvider
	Oidc        *OIDCProvider
}

// SAMLAuthentication represents this authentication type implements the SAML 2.0 Web Browser SSO Profile.
type SAMLAuthentication struct {
	AuthenticationMethod
	Name graphql.String
}

// UsernameAndPasswordAuthentication represents username and password authentication. The underlying authentication mechanism is configured by the server, e.g. LDAP.
type UsernameAndPasswordAuthentication struct {
	AuthenticationMethod
	Name graphql.String
}

type AuthenticationMethodAuth struct {
	AuthType graphql.String
}

type OidcIdentityProviderAuth struct {
	AuthenticationMethodAuth
	RedirectURL       graphql.String
	AuthType          graphql.String
	Name              graphql.String
	Scopes            []graphql.String
	ServiceName       graphql.String
	AuthorizeEndpoint graphql.String
	ClientID          graphql.String
	FederatedIdp      *graphql.String
}

type SamlIdentityProviderAuth struct {
	AuthenticationMethodAuth
	Name     graphql.String
	AuthType graphql.String
}

// ClusterConnection represents a cluster connection.
type ClusterConnection struct {
	ID          graphql.String
	ClusterID   graphql.String
	Tags        []ClusterConnectionTag
	QueryPrefix graphql.String
}

// LocalClusterConnection represents a local cluster connection.
type LocalClusterConnection struct {
	ClusterConnection
	TargetViewID   graphql.String
	TargetViewName RepoOrViewName
	TargetViewType LocalTargetType
	ID             graphql.String
	ClusterID      graphql.String
	Tags           []ClusterConnectionTag
	QueryPrefix    graphql.String
}

// RemoteClusterConnection represents a remote cluster connection.
type RemoteClusterConnection struct {
	ClusterConnection
	PublicURL   graphql.String
	ID          graphql.String
	ClusterID   graphql.String
	Tags        []ClusterConnectionTag
	QueryPrefix graphql.String
}

// ClusterConnectionStatus represents the status of a cluster connection.
type ClusterConnectionStatus struct {
	ID            *graphql.String
	IsValid       graphql.Boolean
	ErrorMessages []ConnectionAspectErrorType
}

// LocalClusterConnectionStatus represents the status of a local cluster connection.
type LocalClusterConnectionStatus struct {
	ClusterConnectionStatus
	ViewName      *graphql.String
	ID            *graphql.String
	IsValid       graphql.Boolean
	ErrorMessages []ConnectionAspectErrorType
}

// RemoteClusterConnectionStatus represents the status of a remote cluster connection.
type RemoteClusterConnectionStatus struct {
	ClusterConnectionStatus
	RemoteViewName            *graphql.String
	RemoteServerVersion       *graphql.String
	RemoteServerCompatVersion *graphql.String
	ID                        *graphql.String
	IsValid                   graphql.Boolean
	ErrorMessages             []ConnectionAspectErrorType
}

// DashboardParameter represents represents a dashboard parameter.
type DashboardParameter struct {
	ID                 graphql.String
	Label              graphql.String
	DefaultValueV2     *graphql.String
	Order              *graphql.Int
	IsMultiParam       *graphql.Boolean
	DefaultMultiValues *[]graphql.String
}

// FileDashboardParameter represents a dashboard parameter where suggestions are taken from uploaded files.
type FileDashboardParameter struct {
	DashboardParameter
	FileName             graphql.String
	ValueColumn          graphql.String
	LabelColumn          *graphql.String
	ValueFilters         []FileParameterValueFilter
	InvalidInputPatterns *[]graphql.String
	InvalidInputMessage  *graphql.String
	ID                   graphql.String
	Label                graphql.String
	DefaultValueV2       *graphql.String
	Order                *graphql.Int
	IsMultiParam         *graphql.Boolean
	DefaultMultiValues   *[]graphql.String
}

// FixedListDashboardParameter represents a dashboard parameter with a fixed list of values to select from.
type FixedListDashboardParameter struct {
	DashboardParameter
	Values             []FixedListParameterOption
	ID                 graphql.String
	Label              graphql.String
	DefaultValueV2     *graphql.String
	Order              *graphql.Int
	IsMultiParam       *graphql.Boolean
	DefaultMultiValues *[]graphql.String
}

// FreeTextDashboardParameter represents a dashboard parameter without restrictions or suggestions.
type FreeTextDashboardParameter struct {
	DashboardParameter
	InvalidInputPatterns *[]graphql.String
	InvalidInputMessage  *graphql.String
	ID                   graphql.String
	Label                graphql.String
	DefaultValueV2       *graphql.String
	Order                *graphql.Int
	IsMultiParam         *graphql.Boolean
	DefaultMultiValues   *[]graphql.String
}

// QueryBasedDashboardParameter represents a dashboard parameter where suggestions are sourced from query results from Humio.
type QueryBasedDashboardParameter struct {
	DashboardParameter
	QueryString           graphql.String
	TimeWindow            graphql.String
	OptionValueField      graphql.String
	OptionLabelField      graphql.String
	UseDashboardTimeIfSet graphql.Boolean
	InvalidInputPatterns  *[]graphql.String
	InvalidInputMessage   *graphql.String
	ID                    graphql.String
	Label                 graphql.String
	DefaultValueV2        *graphql.String
	Order                 *graphql.Int
	IsMultiParam          *graphql.Boolean
	DefaultMultiValues    *[]graphql.String
}

// EventForwarder represents an event forwarder.
type EventForwarder struct {
	ID          graphql.String
	Name        graphql.String
	Description graphql.String
	Enabled     graphql.Boolean
}

// KafkaEventForwarder represents a Kafka event forwarder.
type KafkaEventForwarder struct {
	EventForwarder
	Topic       graphql.String
	Properties  graphql.String
	ID          graphql.String
	Name        graphql.String
	Description graphql.String
	Enabled     graphql.Boolean
}

// IdentityProviderAuthentication represents an Identity Provider.
type IdentityProviderAuthentication struct {
	ID              graphql.String
	Name            graphql.String
	DefaultIdp      graphql.Boolean
	HumioManaged    graphql.Boolean
	LazyCreateUsers graphql.Boolean
	Domains         []graphql.String
	Debug           graphql.Boolean
}

type OidcIdentityProvider struct {
	IdentityProviderAuthentication
	ID                      graphql.String
	Name                    graphql.String
	ClientID                graphql.String
	ClientSecret            graphql.String
	Domains                 []graphql.String
	Issuer                  graphql.String
	TokenEndpointAuthMethod graphql.String
	UserClaim               graphql.String
	Scopes                  []graphql.String
	UserInfoEndpoint        *graphql.String
	RegistrationEndpoint    *graphql.String
	TokenEndpoint           *graphql.String
	GroupsClaim             *graphql.String
	JwksEndpoint            *graphql.String
	AuthenticationMethod    AuthenticationMethodAuth
	AuthorizationEndpoint   *graphql.String
	Debug                   graphql.Boolean
	FederatedIdp            *graphql.String
	ScopeClaim              *graphql.String
	DefaultIdp              graphql.Boolean
	HumioManaged            graphql.Boolean
	LazyCreateUsers         graphql.Boolean
}

// SamlIdentityProvider represents a SAML Identity Provider.
type SamlIdentityProvider struct {
	IdentityProviderAuthentication
	ID                       graphql.String
	Name                     graphql.String
	Domains                  []graphql.String
	GroupMembershipAttribute *graphql.String
	IdpCertificateInBase64   graphql.String
	IdpEntityID              graphql.String
	SignOnURL                graphql.String
	AuthenticationMethod     AuthenticationMethodAuth
	UserAttribute            *graphql.String
	AdminAttribute           *graphql.String
	AdminAttributeMatch      *graphql.String
	DefaultIdp               graphql.Boolean
	HumioManaged             graphql.Boolean
	LazyCreateUsers          graphql.Boolean
	Debug                    graphql.Boolean
}

// License represents represents information about the Humio instance.
type License struct {
	ExpiresAt DateTime
	IssuedAt  DateTime
}

// OnPremLicense represents represents information about a Humio License.
type OnPremLicense struct {
	License
	ExpiresAt DateTime
	IssuedAt  DateTime
	UID       graphql.String
	MaxUsers  *graphql.Int
	Owner     graphql.String
	IsSaaS    graphql.Boolean
	IsOem     graphql.Boolean
}

// TrialLicense represents represents information about an on-going trial of Humio.
type TrialLicense struct {
	License
	ExpiresAt DateTime
	IssuedAt  DateTime
}

// QueryOwnership represents query ownership.
type QueryOwnership struct {
	ID graphql.String
}

// OrganizationOwnership represents query running with organization based ownership.
type OrganizationOwnership struct {
	QueryOwnership
	Organization Organization
	ID           graphql.String
}

// UserOwnership represents query running with user based ownership.
type UserOwnership struct {
	QueryOwnership
	User *User
	ID   graphql.String
}

// SearchDomain represents common interface for Repositories and Views.
type SearchDomain struct {
	ID                   graphql.String
	Name                 RepoOrViewName
	Description          *graphql.String
	DeletedDate          *Long
	PermanentlyDeletedAt *Long
	IsStarred            graphql.Boolean
	PackageV2            Package2
	PackageVersions      []RegistryPackageVersionInfo
	AvailablePackages    []PackageRegistrySearchResultItem
	InstalledPackages    []PackageInstallation
	HasPackageInstalled  graphql.Boolean
	Users                []User
	UsersAndGroups       UsersAndGroupsSearchResultSet
	UsersV2              Users
	Groups               []Group
	StarredFields        []graphql.String
	RecentQueriesV2      []RecentQuery
	AutomaticSearch      graphql.Boolean
	IsActionAllowed      graphql.Boolean
	AllowedViewActions   []ViewAction
	ViewerQueryPrefix    graphql.String
	Tags                 []graphql.String
	Interactions         []ViewInteraction
	Alert                Alert
	Alerts               []Alert
	Dashboard            Dashboard
	Dashboards           []Dashboard
	FilterAlert          FilterAlert
	FilterAlerts         []FilterAlert
	AggregateAlert       AggregateAlert
	AggregateAlerts      []AggregateAlert
	ScheduledSearch      ScheduledSearch
	ScheduledSearches    []ScheduledSearch
	Action               Action
	Actions              []Action
	SavedQuery           SavedQuery
	SavedQueries         []SavedQuery
	DefaultQuery         *SavedQuery
	Files                []File
	ScheduledReports     []ScheduledReport
	ScheduledReport      *ScheduledReport
}

// Repository represents a repository stores ingested data, configures parsers and data retention policies.
type Repository struct {
	SearchDomain
	Type                         RepositoryType
	DataType                     RepositoryDataType
	Limit                        *LimitV2
	IngestBlock                  *DateTime
	UsageTag                     *graphql.String
	Datasources                  []Datasource
	UncompressedByteSize         Long
	CompressedByteSize           Long
	UncompressedByteSizeOfMerged Long
	CompressedByteSizeOfMerged   Long
	TimeOfLatestIngest           *DateTime
	TimeBasedRetention           *graphql.Float
	IngestSizeBasedRetention     *graphql.Float
	IngestTokens                 []IngestToken
	StorageSizeBasedRetention    *graphql.Float
	TimeBasedBackupRetention     *graphql.Float
	IngestListeners              []IngestListener
	MaxAutoShardCount            *graphql.Int
	S3ArchivingConfiguration     *S3Configuration
	CachePolicy                  *CachePolicy
	EffectiveCachePolicy         CachePolicy
	CurrentTagGroupings          []TagGroupingRule
	EventForwardingRules         []EventForwardingRule
	EventForwardersForSelection  []EventForwarderForSelection
	FdrFeed                      FdrFeed
	FdrFeeds                     []FdrFeed
	FdrFeedControl               FdrFeedControl
	FdrFeedControls              []FdrFeedControl
	IngestFeed                   IngestFeed
	IngestFeeds                  IngestFeedQueryResultSet
	AwsExternalID                graphql.String
	Parser                       *Parser
	Parsers                      []Parser
	ID                           graphql.String
	Name                         RepoOrViewName
	Description                  *graphql.String
	DeletedDate                  *Long
	PermanentlyDeletedAt         *Long
	IsStarred                    graphql.Boolean
	PackageV2                    Package2
	PackageVersions              []RegistryPackageVersionInfo
	AvailablePackages            []PackageRegistrySearchResultItem
	InstalledPackages            []PackageInstallation
	HasPackageInstalled          graphql.Boolean
	Users                        []User
	UsersAndGroups               UsersAndGroupsSearchResultSet
	UsersV2                      Users
	Groups                       []Group
	StarredFields                []graphql.String
	RecentQueriesV2              []RecentQuery
	AutomaticSearch              graphql.Boolean
	IsActionAllowed              graphql.Boolean
	AllowedViewActions           []ViewAction
	ViewerQueryPrefix            graphql.String
	Tags                         []graphql.String
	Interactions                 []ViewInteraction
	Alert                        Alert
	Alerts                       []Alert
	Dashboard                    Dashboard
	Dashboards                   []Dashboard
	FilterAlert                  FilterAlert
	FilterAlerts                 []FilterAlert
	AggregateAlert               AggregateAlert
	AggregateAlerts              []AggregateAlert
	ScheduledSearch              ScheduledSearch
	ScheduledSearches            []ScheduledSearch
	Action                       Action
	Actions                      []Action
	SavedQuery                   SavedQuery
	SavedQueries                 []SavedQuery
	DefaultQuery                 *SavedQuery
	Files                        []File
	ScheduledReports             []ScheduledReport
	ScheduledReport              *ScheduledReport
}

// View represents represents information about a view, pulling data from one or several repositories.
type View struct {
	SearchDomain
	Connections             []ViewConnection
	CrossOrgConnections     []CrossOrgViewConnection
	ClusterConnections      []ClusterConnection
	ClusterConnection       ClusterConnection
	CheckClusterConnections []ClusterConnectionStatus
	IsFederated             graphql.Boolean
	ID                      graphql.String
	Name                    RepoOrViewName
	Description             *graphql.String
	DeletedDate             *Long
	PermanentlyDeletedAt    *Long
	IsStarred               graphql.Boolean
	PackageV2               Package2
	PackageVersions         []RegistryPackageVersionInfo
	AvailablePackages       []PackageRegistrySearchResultItem
	InstalledPackages       []PackageInstallation
	HasPackageInstalled     graphql.Boolean
	Users                   []User
	UsersAndGroups          UsersAndGroupsSearchResultSet
	UsersV2                 Users
	Groups                  []Group
	StarredFields           []graphql.String
	RecentQueriesV2         []RecentQuery
	AutomaticSearch         graphql.Boolean
	IsActionAllowed         graphql.Boolean
	AllowedViewActions      []ViewAction
	ViewerQueryPrefix       graphql.String
	Tags                    []graphql.String
	Interactions            []ViewInteraction
	Alert                   Alert
	Alerts                  []Alert
	Dashboard               Dashboard
	Dashboards              []Dashboard
	FilterAlert             FilterAlert
	FilterAlerts            []FilterAlert
	AggregateAlert          AggregateAlert
	AggregateAlerts         []AggregateAlert
	ScheduledSearch         ScheduledSearch
	ScheduledSearches       []ScheduledSearch
	Action                  Action
	Actions                 []Action
	SavedQuery              SavedQuery
	SavedQueries            []SavedQuery
	DefaultQuery            *SavedQuery
	Files                   []File
	ScheduledReports        []ScheduledReport
	ScheduledReport         *ScheduledReport
}

// Token represents a token.
type Token struct {
	ID         graphql.String
	Name       graphql.String
	ExpireAt   *Long
	IPFilter   *graphql.String
	IPFilterV2 *IPFilter
	CreatedAt  Long
}

// OrganizationPermissionsToken represents organization permissions token. The token allows the caller to work with organization-level permissions.
type OrganizationPermissionsToken struct {
	Token
	Permissions []graphql.String
	ID          graphql.String
	Name        graphql.String
	ExpireAt    *Long
	IPFilter    *graphql.String
	IPFilterV2  *IPFilter
	CreatedAt   Long
}

// SystemPermissionsToken represents system permissions token. The token allows the caller to work with system-level permissions.
type SystemPermissionsToken struct {
	Token
	Permissions []graphql.String
	ID          graphql.String
	Name        graphql.String
	ExpireAt    *Long
	IPFilter    *graphql.String
	IPFilterV2  *IPFilter
	CreatedAt   Long
}

// ViewPermissionsToken represents view permissions token. The token allows the caller to work with the same set of view-level permissions across multiple views.
type ViewPermissionsToken struct {
	Token
	Permissions []graphql.String
	Views       []SearchDomain
	ID          graphql.String
	Name        graphql.String
	ExpireAt    *Long
	IPFilter    *graphql.String
	IPFilterV2  *IPFilter
	CreatedAt   Long
}

// PersonalUserToken represents personal token for a user. The token will inherit the same permissions as the user.
type PersonalUserToken struct {
	Token
	ID         graphql.String
	Name       graphql.String
	ExpireAt   *Long
	IPFilter   *graphql.String
	IPFilterV2 *IPFilter
	CreatedAt  Long
}

// Widget represents a dashboard widget.
type Widget struct {
	ID          graphql.String
	Title       graphql.String
	Description *graphql.String
	X           graphql.Int
	Y           graphql.Int
	Width       graphql.Int
	Height      graphql.Int
}

// LinkWidget represents a widget that lists links to other dashboards.
type LinkWidget struct {
	Widget
	Labels      []graphql.String
	ID          graphql.String
	Title       graphql.String
	Description *graphql.String
	X           graphql.Int
	Y           graphql.Int
	Width       graphql.Int
	Height      graphql.Int
}

// NoteWidget represents a widget get text, links, etc.
type NoteWidget struct {
	Widget
	BackgroundColor *graphql.String
	TextColor       *graphql.String
	Text            graphql.String
	ID              graphql.String
	Title           graphql.String
	Description     *graphql.String
	X               graphql.Int
	Y               graphql.Int
	Width           graphql.Int
	Height          graphql.Int
}

// QueryBasedWidget represents a widget with a visualization of a query result.
type QueryBasedWidget struct {
	Widget
	QueryString  graphql.String
	Start        graphql.String
	End          graphql.String
	IsLive       graphql.Boolean
	WidgetType   graphql.String
	Options      *JSON
	Interactions []QueryBasedWidgetInteraction
	ID           graphql.String
	Title        graphql.String
	Description  *graphql.String
	X            graphql.Int
	Y            graphql.Int
	Width        graphql.Int
	Height       graphql.Int
}

// contractual represents common interface for contractual parts of the limit.
type Contractual struct {
	IncludeUsage graphql.Boolean
}

type Ignored struct {
	contractual
	IncludeUsage graphql.Boolean
}

type Limited struct {
	contractual
	Limit        Long
	IncludeUsage graphql.Boolean
}

type Unlimited struct {
	contractual
	IncludeUsage graphql.Boolean
}
